spring:
  http:
    gzip:
      mimeTypes: application/json
server:
  contextPath: /${spring.application.name}/v${spring.application.majorVersion}
  port: ${port:8180}
endpoints:
  health:
    sensitive: false
management:
  contextPath: /admin
  security:
    enabled: false
security:
  basic:
    enabled: false
springfox:
  documentation:
    swagger:
      v2:
        path: /docs/api
info:
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
contact:
  name: Gregor Zurowski
  url: http://www.cinteo.com
  email: gregor@zurowski.net
